version: "3"
services:
  pgcli:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod.finops
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: /bin/sh
